language: scala
scala:
  - 2.11.8
sudo: false
script:
  - sbt compile
  - sbt scalastyle
  - sbt test
notifications:
  slack:
    secure: sbNtT/v7f5Svvw0JvYbnXsffvEe0SYBYapIO/3cBU+SYg1uILukufIgUVBNADgKCp/z1iTVwplYEUOi2OaRAENW5511+ZhAJaweebIqVbrb6zleheSsRU8N6ROLVWTO4ZY4i93OhOs+0oGTVJod99XIwGnk73Y/f5OehVrFbltU0r9Wu5FrM531bAeyySe7fR0+x5TjLJqIEU+IwaZNBfwEC0naEeWdmSXPr0cyPTFSpiIIReVRrKCZsJghGqnIiSXr4nyy4BPtNjy4fz5Ckc898JHV7L9Zlc+39Tv/dzy3m203d1LfN+WqHkJmCT/wkmU1KxmNaKJnTqfUyHyB6K/zjHu5H2+ad13lImV9p+NOtVQNyUkyPxFhbB8GtiQNUrukWfHSj/UEoTACqwYS58ihwkGyQmdoeTagp23iPQyFMc1My6oTRXFypu4cUb5pUVP6fpvW9aWYKAYdzQw1epobTAgHd4gfu7dSyeZ0dMBPC3016PLeMFbQ4Q+t+7p9pbgw/xPYgiinVDduYHNLJgz639ULIKw3FDk4hbgZnT1pHb5/glLn7V+KANX8ekgpQMBfen6l5Fkm6nhsc+4pO0HOrhWKyLevxn7tzgMKFq47VYb6O+vkahehct5P17yilX3IJmC/wz2aoJxS88d+Zijl3S702qRzx9yoOqDvb3uU=
